workspace(name = "rules_pcl_example")

# In your WORKSPACE file, you'll make this an http_archive instead. See README.md.
local_repository(
    name = "rules_pcl",
    path = "..",
)

load("@rules_pcl//bzl:pcl_deps.bzl", "pcl_deps")
pcl_deps()

# NOTE: This must be loaded after the call to pcl_deps().
load("@rules_pcl//bzl:pcl_repositories.bzl", "pcl_repositories")
pcl_repositories()
