workspace(name = "rules_pcl_example")

# In your WORKSPACE file, you'll make this an http_archive instead. See README.md.
local_repository(
    name = "rules_pcl",
    path = "..",
)

load("@rules_pcl//bzl:repositories.bzl", "pcl_repositories")
pcl_repositories()

# NOTE: This must be loaded after the call to pcl_repositories().
load("@rules_pcl//bzl:init_deps.bzl", "pcl_init_deps")
pcl_init_deps()
