on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 x86_64

    steps:
      - uses: actions/checkout@v2.1.0
      - run: |
          curl -sL https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64 -o /tmp/bazel
          chmod 755 /tmp/bazel

      - run: |
          cd example && /tmp/bazel test "@pcl//..."

  test_embedded:
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          # nvidia jetson
          - arch: aarch64
            distro: ubuntu18.04
          # raspberry pi
          - arch: armv7
            distro: ubuntu18.04

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build and run tests on embedded platforms
        #id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          run: |
            curl -sL https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64 -o /tmp/bazel
            chmod 755 /tmp/bazel
            cd example && /tmp/bazel test "@pcl//..."
