on: [push]

jobs:
  build_x86-64:
    name: Build on ubuntu22.04 x86_64
    runs-on: ubuntu-22.04
    timeout-minutes: 720

    steps:
      - uses: actions/checkout@v3.5.3
      - run: |
          curl -sL https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64 -o /tmp/bazel
          chmod 755 /tmp/bazel
          cd example

      - run: |
          cd example && /tmp/bazel test "@pcl//..." --verbose_failures --show_progress_rate_limit=10

  build_aarch64:
    name: Build on ubuntu22.04 aarch64
    runs-on: ubuntu-22.04
    timeout-minutes: 720

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: uraimo/run-on-arch-action@v2.5.0
        name: Build and run tests on embedded platforms
        with:
          arch: aarch64
          distro: ubuntu22.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            apt-get update -q -y
            apt-get install -q -y curl gcc g++
            curl -sL https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-arm64 -o /usr/bin/bazel
            chmod 755 /usr/bin/bazel

          run: |
            # Skip running tests because the emulated environment is super slow, so many tests would
            # timeout and fail.
            cd example && bazel build "@pcl//..." --verbose_failures --show_progress_rate_limit=10
